import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import MainLayout from "@/components/MainLayout";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>
          <div className="flex rounded-lg">
            <SideBar />
            <div className="w-full">
              <Header />
              {children}
            </div>
          </div>
        </MainLayout>
      </body>
    </html>
  );
}
